 Richiede un modello allenato "model.keras" e i 52 dataset preprocessati in una cartella data

In [2]:
import scipy.io
import tensorflow  as tf
import numpy as np
from tensorflow import keras
model=keras.models.load_model("model.keras") 
with open("Measure.txt", "w+") as writer:      
    for asd in range(1,53):
        
        time_step =[]
        temps = []
        temporanea=[]
        if asd<10:
            asd="0"+str(asd)
        else:
            asd=str(asd)
        writer.writelines(asd+":\n")
        dataset = scipy.io.loadmat('data\\AfterPreprocessingMetricsNoITD'+asd+'.mat')#
        dataset=dataset["newMatrix"]#["ExportMatrix"]#
        print(len(dataset))


        data1=np.array(dataset)
        print(data1.shape)

        for row in range(len(dataset)) :
            for i in range(3):

                if(i==0):
                    time_step.append([1,0,0])
                elif(i==1):
                    time_step.append([0,1,0])
                else:
                    time_step.append([0,0,1])
                temps.append(dataset[row,i,:,:])
        series = np.array(temps)
        time = np.array(time_step)
        indices = np.arange(series.shape[0])
        np.random.shuffle(indices)
        print(series.shape)
        predictions = model.predict(series[0][0])
        predictions=np.argmax(predictions,axis=1)
        print(predictions)
        y_test=np.argmax(time,axis=1)
        import matplotlib.pyplot as plt

        from sklearn.metrics import confusion_matrix
        cm = confusion_matrix(y_test,predictions)
        cm =np.array(cm)
        total=sum(sum(cm))
        cont=0
        labels = ['right', 'left','steady']
        diagonal=cm[0,0]+cm[1,1]+cm[2,2]
        print(cm)
        for row in cm:
            TP=row[cont]
            FN=sum(row)-row[cont]
            FP=sum(cm[:,cont])-row[cont]
            TN=diagonal-row[cont]
            accuracy=str(np.around((TP+TN)/(TP+TN+FN+FP),4))
            precision=str(np.around(TP/(TP+FP),4))
            recall=str(np.around(TP/(TP+FN),4))
            specificity=str(np.around(TN/(TN+FP),4))
            writer.writelines(labels[cont]+":\t"+"accuracy:"+accuracy+"\t"+"precision:"+precision+"\t"+"recall:"+recall+"\t"+"specificity:"+specificity+"\n")
            cont=cont+1


FileNotFoundError: [Errno 2] No such file or directory: 'data\\AfterPreprocessingMetricsNoITD01.mat'

In [7]:
import scipy.io
import tensorflow  as tf
import numpy as np
from tensorflow import keras
model=keras.models.load_model("model2.keras") 
model.summary()
a1=np.random.rand(32,10,1536)
model.predict(a1)
a2=np.random.rand(32,10,1536)
model.predict(a2)
model=keras.models.load_model("model.keras") 
model.summary()
a1=np.random.rand(32,10,32)
model.predict(a1)
a2=np.random.rand(32,10,32)
model.predict(a2)

Model: "functional_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ input_layer_1 (InputLayer)      │ (None, 10, 1536)       │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ reshape (Reshape)               │ (None, 1, 10, 1536)    │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ functional (Functional)         │ (None, 3)              │        18,947 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 43,019 (168.05 KB)

 Trainable params: 12,035 (47.01 KB)

 Non-trainable params: 6,912 (27.00 KB)

 Optimizer params: 24,072 (94.04 KB)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 362ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 133ms/step


Model: "functional_7"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ input_layer_3 (InputLayer)      │ (None, 10, 32)         │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ reshape_1 (Reshape)             │ (None, 1, 10, 32)      │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ functional_5 (Functional)       │ (None, 128)            │       267,584 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (None, 3)              │           387 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 803,531 (3.07 MB)

 Trainable params: 267,779 (1.02 MB)

 Non-trainable params: 192 (768.00 B)

 Optimizer params: 535,560 (2.04 MB)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 262ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step


array([[3.44231762e-23, 1.44233509e-32, 1.00000000e+00],
       [1.00000000e+00, 0.00000000e+00, 4.19859619e-10],
       [6.86659325e-19, 2.42979694e-27, 1.00000000e+00],
       [5.67511082e-18, 0.00000000e+00, 1.00000000e+00],
       [1.00000000e+00, 7.13620119e-28, 6.41161702e-09],
       [1.00000000e+00, 3.13004012e-28, 1.28599922e-10],
       [4.97569283e-03, 0.00000000e+00, 9.95024264e-01],
       [5.72852850e-01, 7.03288475e-14, 4.27147150e-01],
       [1.00000000e+00, 0.00000000e+00, 7.07846111e-33],
       [2.78352619e-10, 2.46481577e-26, 1.00000000e+00],
       [5.70489760e-07, 0.00000000e+00, 9.99999404e-01],
       [4.79749113e-04, 1.69914086e-28, 9.99520302e-01],
       [1.48006563e-22, 0.00000000e+00, 1.00000000e+00],
       [3.52315530e-02, 3.65903288e-36, 9.64768469e-01],
       [3.64116026e-09, 1.25132927e-20, 1.00000000e+00],
       [6.11422420e-18, 1.30709556e-37, 1.00000000e+00],
       [4.08752534e-08, 3.42302118e-35, 1.00000000e+00],
       [5.80878770e-13, 4.48386

In [3]:
import scipy.io
import tensorflow  as tf
import numpy as np
from tensorflow import keras
model=keras.models.load_model("modelEmotiv.keras") 
with open("greg.txt", "w+") as writer:      
    
    time_step =[]
    temps = []
    temporanea=[]


    dataset = scipy.io.loadmat('datasetMarco.mat')#
    dataset=dataset["newMatrix"]#["ExportMatrix"]#
    print(len(dataset))


    data1=np.array(dataset)
    print(data1.shape)

    for row in range(len(dataset)) :
        for i in range(3):

            if(i==0):
                time_step.append([1,0,0])
            elif(i==1):
                time_step.append([0,1,0])
            else:
                time_step.append([0,0,1])
            temps.append(dataset[row,i,:,:])
    series = np.array(temps)
    time = np.array(time_step)
    indices = np.arange(series.shape[0])
    np.random.shuffle(indices)
    print(series.shape)
    support_features = model.predict(series[:27])
    # predictions=np.argmax(predictions,axis=1)
    # print(len(predictions))
    # print(np.argmax(time,axis=1))
    y_test=time
    support_labels=y_test[:27]

    from sklearn.neighbors import KNeighborsClassifier
    from sklearn.metrics import accuracy_score

    # Train k-NN classifier
    knn = KNeighborsClassifier(n_neighbors=3)  # You can adjust the number of neighbors
    knn.fit(support_features, support_labels)

    # Predict labels for the support set
    support_predictions = knn.predict(support_features)
    query_features=model.predict(series[27:])
    # Predict labels for the query set
    query_predictions = knn.predict(query_features)

    query_labels=y_test[27:]
    # Calculate accuracy for the support set
    support_accuracy = accuracy_score(support_labels, support_predictions)
    print(f'Support Set Accuracy: {support_accuracy * 100:.2f}%')

    # Calculate accuracy for the query set
    query_accuracy = accuracy_score(query_labels, query_predictions)
    print(f'Query Set Accuracy: {query_accuracy * 100:.2f}%')






    y_test=np.argmax(query_labels,axis=1)
    predictions=np.argmax(query_predictions,axis=1)



    import matplotlib.pyplot as plt

    from sklearn.metrics import confusion_matrix
    cm = confusion_matrix(y_test,predictions)
    cm =np.array(cm)
    total=sum(sum(cm))
    cont=0
    labels = ['right', 'left','steady']
    diagonal=cm[0,0]+cm[1,1]+cm[2,2]
    print(cm)
    for row in cm:
        TP=row[cont]
        FN=sum(row)-row[cont]
        FP=sum(cm[:,cont])-row[cont]
        TN=diagonal-row[cont]
        accuracy=str(np.around((TP+TN)/(TP+TN+FN+FP+0.0001),4))
        precision=str(np.around(TP/(TP+FP+0.0001),4))
        recall=str(np.around(TP/(TP+FN+0.0001),4))
        specificity=str(np.around(TN/(TN+FP+0.0001),4))
        writer.writelines(labels[cont]+":\t"+"accuracy:"+accuracy+"\t"+"precision:"+precision+"\t"+"recall:"+recall+"\t"+"specificity:"+specificity+"\n")
        cont=cont+1


29
(29, 3, 14, 32)
(87, 14, 32)
2/2 [==============================] - 0s 51ms/step
Support Set Accuracy: 100.00%
Query Set Accuracy: 96.67%
[[18  2  0]
 [ 0 20  0]
 [ 0  0 20]]
